# Site settings
baseURL = "https://gracefulhr.com/"
title = "GracefulHR"
languageCode = "en-us"
pagerSize = 10 # Number of posts per page
theme = "amnix"
disqusShortname = "" # Enable comments by entering your Disqus shortname
description = "Graceful tips on working with people."
enableEmoji = true

[Params]
  defaultAuthor = "svitlana" # Default article author. Authors are located in /data/authors
  description = "Working with people on a daily basis" # Site description. Used in meta description
  opengraph = true # Enable OpenGraph
  twitterCards = true # Enable Twitter Cards
  columns = 2
  homeLayout = "2 columns + sidebar" # Configure home page layout
  listLayout = "2 columns + sidebar" # Configure layout for list pages
  singleLayout = "content + sidebar" # Configure layout for single pages
  mainSections = ["post", "about"] # Set main page sections
  dateFormat = "January 02, 2006" # Change the format of dates
  customCSS = ["css/style.css"] # Include custom CSS files
  comments = true # Enable comments for all site pages
  related = true # Enable Related Content (See https://gohugo.io/content-management/related/)
  mathjax = false # Enable MathJax for all site pages
  share = true
  copyrightStartYear = 2022
  copyright = "GracefulHR (Svitlana Orlova)"

[Params.Social] # Site Social block
  email = "contact@gracefulhr.com"
  # facebook = "username"
  twitter = "GracefulHR"
  # telegram = "username"
  linkedin = "svitlana-orlova-60849346"

[Params.sidebar]
  widgets = ["recent", "categories", "tags"]

[Params.Widgets]
  recent = true # Enable "Recent Posts" widget
  recentNum = 5 # Set number of articles in the "Recent articles" widget
  recentDate = true # Show datetime in the "Recent Posts" widget
  categories = true # Enable "Categories" widget
  tags = true # Enable "Tags" widget
  tagsCounter = true # Enable counter for each tag in the "Tags" widget

[Params.Share] # Post Share block
  facebook = true
  twitter = true
  reddit = false
  telegram = true
  linkedin = true
  vk = false
  pocket = false

[Params.Manifest] # Web App Manifest config
  name = "GracefulHR"
  shortName = "GracefulHR"
  display = "standalone"
  backgroundColor = "#33333a"
  themeColor = "#5b5b67"
  description = "Graceful tips on working with people."
  orientation = "portrait"
  startUrl = "/"
  scope = "/"

[outputFormats]
  [outputFormats.MANIFEST] # Add custom MANIFEST output format
    mediaType = "application/json"
    baseName = "manifest"
    isPlainText = true
    notAlternative = true

[outputs]
  home = ["HTML", "RSS", "MANIFEST"] # Include MANIFEST format to home page
[services]
  [services.googleAnalytics]
    id = "G-WB11E4N7NG"
